# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: test-and-build

on: # 이벤트 트리거
  pull_request:
    branches: [ "develop" ]

permissions:
  checks: write
  pull-requests: write

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout branch
      uses: actions/checkout@v3 #https://github.com/marketplace/actions/checkout < actions 주소
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
    - name: Setup Gradle permission
      run: chmod +x ./gradlew 
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: test with Gradle
      run: ./gradlew test
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        junit_files: "build/test-results/junit/**/*.xml"
    - name: build with Gradle
      run: ./gradlew build -x test
    
        
